list: $/moonwalkerz/trustpilot/models/review/columns.yaml
modelClass: MoonWalkerz\Trustpilot\Models\Review
title: Reviews
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'moonwalkerz/trustpilot/reviews/update/:id'
